# Generated by Django 4.2.5 on 2023-10-22 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('editorial', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('precio', models.CharField(max_length=10)),
                ('oferta', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Portada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas')),
                ('previa_img1', models.ImageField(blank=True, null=True, upload_to='previas')),
                ('previa_img2', models.ImageField(blank=True, null=True, upload_to='previas')),
                ('book', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LibrosApp.libro')),
            ],
        ),
    ]
