# Generated by Django 4.2.5 on 2023-10-22 02:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LibrosApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.CharField(blank=True, max_length=10, null=True)),
                ('oferta', models.CharField(blank=True, max_length=5, null=True)),
                ('pago', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibrosApp.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
